# Generated by Django 4.1.2 on 2023-03-11 12:00

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schooluser",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 11, 17, 0, 14, 960327)
            ),
        ),
        migrations.AlterField(
            model_name="schooluser",
            name="phonenumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=13, region=None, unique=True
            ),
        ),
    ]
