# Generated by Django 4.1.2 on 2023-03-09 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 3, 10, 0, 25, 26, 347069)
            ),
        ),
    ]
