# Generated by Django 4.1.2 on 2023-03-11 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_schooluser_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schooluser",
            name="date_joined",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
