# Generated by Django 4.1.2 on 2023-03-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_schooluser_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schooluser",
            name="date_joined",
            field=models.DateField(),
        ),
    ]
