# Generated by Django 4.1.2 on 2023-03-16 16:29

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        choices=[
                            ("Nursery", "Nursery"),
                            ("KG-1", "KG-1"),
                            ("KG-2", "KG-2"),
                            ("PlayGroup", "PlayGroup"),
                            ("I", "I"),
                            ("II", "II"),
                            ("III", "III"),
                            ("IV", "IV"),
                            ("V", "V"),
                            ("VI", "VI"),
                            ("VII", "VII"),
                            ("VIII", "VIII"),
                            ("IX", "IX"),
                            ("X", "X"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                            ("I", "I"),
                            ("J", "J"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=70)),
                ("last_name", models.CharField(max_length=70)),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "classroom",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.classroom",
                    ),
                ),
            ],
        ),
    ]
