# Generated by Django 4.1.2 on 2023-03-25 12:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="contact_number_pr",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=13, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="contact_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=13, region=None, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
