# Generated by Django 4.1.2 on 2023-03-16 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_alter_teacher_classroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="classroom",
        ),
        migrations.AddField(
            model_name="classroom",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.teacher",
            ),
            preserve_default=False,
        ),
    ]
