# Generated by Django 4.1.2 on 2023-03-16 17:32

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_remove_teacher_classroom_classroom_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="class_name",
            field=models.CharField(
                choices=[
                    ("Other", "Other"),
                    ("Nursery", "Nursery"),
                    ("KG-1", "KG-1"),
                    ("KG-2", "KG-2"),
                    ("PlayGroup", "PlayGroup"),
                    ("I", "I"),
                    ("II", "II"),
                    ("III", "III"),
                    ("IV", "IV"),
                    ("V", "V"),
                    ("VI", "VI"),
                    ("VII", "VII"),
                    ("VIII", "VIII"),
                    ("IX", "IX"),
                    ("X", "X"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="contact_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=13, region=None
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name_st", models.CharField(max_length=20)),
                ("last_name_st", models.CharField(max_length=20)),
                ("roll_no", models.IntegerField(unique=True)),
                ("dob", models.DateField()),
                ("last_grade", models.CharField(blank=True, max_length=20)),
                ("first_name_gr", models.CharField(max_length=20)),
                ("last_name_gr", models.CharField(max_length=20)),
                (
                    "contact_number_gr",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=13, region=None
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.classroom",
                    ),
                ),
            ],
        ),
    ]
