# Generated by Django 4.1.2 on 2023-03-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0005_subjects_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exams",
            name="class_room",
        ),
        migrations.AddField(
            model_name="exams",
            name="class_room",
            field=models.ManyToManyField(to="school.classroom"),
        ),
    ]
