# Generated by Django 4.1.2 on 2023-03-23 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0006_remove_exams_class_room_exams_class_room"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subjects",
            new_name="Subject",
        ),
    ]
