# Generated by Django 4.1.2 on 2023-03-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0008_rename_exams_exam_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("address", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_title",
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
