# Generated by Django 4.1.2 on 2023-03-12 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monthlysubscription",
            old_name="data_paid",
            new_name="date_paid",
        ),
    ]
